# Generated by Django 4.2.8 on 2024-01-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_messagequery_has_responded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSubcriber',
            new_name='EmailSubscriber',
        ),
    ]
