# Generated by Django 3.2.9 on 2021-11-05 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nexcodeix.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=nexcodeix.common.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('batch_category', models.CharField(choices=[('PY', 'PYTHON'), ('DJ', 'DJANGO'), ('FS', 'FLASK')], max_length=2)),
                ('started', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('per_week', models.IntegerField(default=2)),
                ('days', models.CharField(blank=True, max_length=4, null=True)),
                ('time_starts', models.TimeField(blank=True, null=True)),
                ('time_ends', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BatchClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=4, null=True)),
                ('started', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('time_starts', models.TimeField(blank=True, null=True)),
                ('time_ends', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='batch/class/video')),
                ('git_link', models.CharField(blank=True, max_length=2040, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='batch/class/files')),
                ('batch_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batch.batchclass')),
            ],
        ),
        migrations.CreateModel(
            name='BatchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'batch')},
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='user',
            field=models.ManyToManyField(related_name='batches', through='batch.BatchUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
