# Generated by Django 3.2.9 on 2021-11-02 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='batch',
            name='days',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='per_week',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='batch',
            name='time_ends',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='time_starts',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='batchuser',
            unique_together={('user', 'batch')},
        ),
    ]
