# Generated by Django 3.2.9 on 2021-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_alter_batchclass_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchuser',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='batchuser',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchuser',
            name='verified_for_batch',
            field=models.BooleanField(default=False),
        ),
    ]
