# Generated by Django 3.2.9 on 2021-11-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_auto_20211104_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClassMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='batch/class/video')),
                ('git_link', models.CharField(blank=True, max_length=2040, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='batch/class/files')),
                ('batch_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='batch.batchclass')),
            ],
        ),
    ]
