# Generated by Django 3.2.9 on 2021-11-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_auto_20211105_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-date_created']},
        ),
    ]
