# Generated by Django 3.2.9 on 2021-11-05 06:49

import batch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_alter_batch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.UUIDField(default=batch.models.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
