# Generated by Django 4.2.8 on 2023-12-29 07:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
