# Generated by Django 3.2.9 on 2021-11-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
