# Generated by Django 3.2.9 on 2021-11-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_auto_20211119_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchclass',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
