# Generated by Django 3.2.9 on 2021-11-26 03:07

from django.db import migrations, models
import django.db.models.deletion
import nexcodeix.common


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_alter_batchclass_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchImportantAnouncement',
            fields=[
                ('id', models.UUIDField(default=nexcodeix.common.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('anouncement', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
