# Generated by Django 3.2.9 on 2021-11-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_batchimportantanouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchimportantanouncement',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
