# Generated by Django 3.2.9 on 2021-12-01 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nexcodeix.common


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batches', '0005_alter_batchimportantanouncement_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassJoinedUser',
            fields=[
                ('id', models.UUIDField(default=nexcodeix.common.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('J', 'JOINED'), ('P', 'PENDING'), ('N', 'NOT JOINED')], max_length=1)),
                ('batch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_users', to='batches.batchclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
