# Generated by Django 3.2.9 on 2021-12-01 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batches', '0006_classjoineduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classjoineduser',
            name='status',
            field=models.CharField(choices=[('J', 'JOINED'), ('P', 'PENDING'), ('N', 'NOT JOINED')], default='P', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='classjoineduser',
            unique_together={('batch_class', 'user')},
        ),
    ]
