# Generated by Django 3.2.9 on 2021-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0008_batch_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classjoineduser',
            name='status',
            field=models.CharField(choices=[('J', 'JOINED'), ('P', 'PENDING'), ('N', 'NOT JOINED')], default='N', max_length=1),
        ),
    ]
