# Generated by Django 4.2.8 on 2024-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('proj_type', models.CharField(max_length=10, verbose_name='Project Type')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
