# Generated by Django 3.2.9 on 2021-11-19 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nexcodeix.common


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerificationOTP',
            fields=[
                ('id', models.UUIDField(default=nexcodeix.common.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=100)),
                ('expired', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
