# Generated by Django 4.2.8 on 2024-01-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
    ]
