# Generated by Django 3.2.9 on 2021-11-05 06:58

from django.db import migrations, models
import nexcodeix.common


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=nexcodeix.common.uuid_without_dash, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
